### ISSUE TITLE
Uncaught exception in between opening of projects

### ISSUE THREAD

**Issue by pmeijer** [webgme/ui-replay#3]
```
TypeError: Cannot read property 'split' of null
  at Object.getBranchStatus(/extlib/node_modules/webgme-ui-replay/src/visualizers/panels/UIReplay/UIReplayControllers.js:72:32)
  at ? (/extlib/node_modules/webgme-ui-replay/src/visualizers/widgets/UIReplay/UIReplayWidget.js:63:49)
  at i(/dist/webgme.2.13.1.lib.build.js:22:16821)
```

https://sentry.io/vanderbilt-university/webgme/issues/279711266/

**Comment by pmeijer** [comment]
closed by 05f1b8a
